//drills
Blocks.mechanicalDrill.drillTime=0.1
Blocks.pneumaticDrill.drillTime=0.1
Blocks.laserDrill.drillTime=0.1
Blocks.blastDrill.drillTime=0.1
Blocks.plasmaBore.drillTime=0.1
Blocks.impactDrill.drillTime=0.1
Blocks.largePlasmaBore.drillTime=0.1
Blocks.eruptionDrill.drillTime=0.1
