//drills
Blocks.mechanicalDrill.drillTime=1
Blocks.mechanicalDrill.hardnessDrillMultiplier=1
Blocks.pneumaticDrill.drillTime=1
Blocks.pneumaticDrill.hardnessDrillMultiplier=1
Blocks.laserDrill.drillTime=1
Blocks.laserDrill.hardnessDrillMultiplier=1
Blocks.blastDrill.drillTime=1
Blocks.blastDrill.hardnessDrillMultiplier=1
Blocks.plasmaBore.drillTime=1
Blocks.impactDrill.drillTime=1
Blocks.largePlasmaBore.drillTime=1
Blocks.eruptionDrill.drillTime=1
